### ISSUE TITLE
XEP-0286: Mobile Considerations

### ISSUE THREAD

**Issue by bheesham** [SteamedPears/rust-xmpp#12]
XEP: http://xmpp.org/extensions/xep-0286.html#xeps
- [ ] #5 XEP-0198: Stream Management
- [ ] #1 XEP-0138: Stream Compression
- [ ] #2 XEP-0322: Efficient XML Interchange (EXI) Format
- [ ] #6 XEP-0357: Push Notifications
- [ ] #4 XEP-0237: Roster Versioning
- [ ] #3 XEP-0115: Entity Capabilities
- [ ] #7 XEP-0313: Message Archive Management
