### ISSUE TITLE
Become transport agnostic.

### ISSUE THREAD

**Issue by bheesham** [SteamedPears/rust-xmpp#13]
- [ ] XEP-0357: Push Notifications #6;
- [ ] Use html5ever #10;
- [ ] Use Cap'n Proto #11.
